"""Command line interface with stable JSON schema and fail-closed errors."""

from __future__ import annotations

import argparse
import json
import platform
import sys
import time
from pathlib import Path

from . import SCHEMA_VERSION, __version__
from .pilot import run_pilot
from .relations import RelationSpecError, analyze_source, discover_relations, production_api, validate_relation


def _bounded(path: str, cwd: Path, *, create_parent: bool = False) -> Path:
    candidate = Path(path).expanduser()
    if not candidate.is_absolute():
        candidate = cwd / candidate
    candidate = candidate.resolve()
    try:
        candidate.relative_to(cwd.resolve())
    except ValueError as exc:
        raise ValueError(f"path must remain inside working directory: {cwd}") from exc
    if create_parent:
        candidate.parent.mkdir(parents=True, exist_ok=True)
    return candidate


def _emit(payload: dict, as_json: bool) -> None:
    if as_json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        print(f"ZoracleFlux {payload.get('version', __version__)} | schema {payload.get('schema_version', SCHEMA_VERSION)}")
        print(payload.get("summary", payload.get("status", "ok")))
        for row in payload.get("relations", []):
            print(f"  {row['status']:7} {row['relation']}")


def _audit(cwd: Path, event: str, status: str) -> None:
    audit = cwd / ".zoracleflux" / "audit.jsonl"
    audit.parent.mkdir(exist_ok=True)
    record = {"schema_version": SCHEMA_VERSION, "event": event, "status": status,
              "network": False, "model_calls": 0, "timestamp_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}
    with audit.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(record, sort_keys=True) + "\n")


def check(args: argparse.Namespace) -> int:
    cwd = Path.cwd()
    started = time.perf_counter()
    try:
        if args.source:
            path = _bounded(args.source, cwd)
            payload = {"schema_version": SCHEMA_VERSION, "version": __version__, "command": "check",
                       "status": "not-executed", "summary": "Source was parsed but never executed; use the built-in fixture or a reviewed adapter.",
                       "analysis": analyze_source(str(path)), "network": False, "model_calls": 0}
            _emit(payload, args.json)
            _audit(cwd, "check-source", "not-executed")
            return 2
        relations = discover_relations()
        outcomes = [validate_relation(r, production_api(), args.timeout_ms) for r in relations]
        bad = [x for x in outcomes if x["status"] != "passed"]
        payload = {"schema_version": SCHEMA_VERSION, "version": __version__, "command": "check",
                   "status": "failed" if bad else "passed",
                   "summary": f"{len(outcomes) - len(bad)}/{len(outcomes)} declared relations passed",
                   "relations": outcomes, "counts": {"total": len(outcomes), "passed": len(outcomes) - len(bad), "failed": len(bad)},
                   "evidence": "bounded deterministic cases; not a proof", "network": False, "model_calls": 0,
                   "elapsed_ms": round((time.perf_counter() - started) * 1000, 3)}
        _emit(payload, args.json)
        _audit(cwd, "check", payload["status"])
        return 1 if bad else 0
    except (OSError, SyntaxError, RelationSpecError, ValueError) as exc:
        payload = {"schema_version": SCHEMA_VERSION, "version": __version__, "command": "check",
                   "status": "error", "error": f"{type(exc).__name__}: {exc}", "network": False, "model_calls": 0}
        _emit(payload, True if args.json else False)
        _audit(cwd, "check", "error")
        return 2


def generate(args: argparse.Namespace) -> int:
    cwd = Path.cwd()
    try:
        output = _bounded(args.output, cwd, create_parent=True)
        relations = discover_relations()
        lines = ['"""Generated by ZoracleFlux; review before committing."""',
                 "from zoracleflux.relations import discover_relations, production_api, validate_relation", "",
                 "RELATIONS = discover_relations()", ""]
        for i, relation in enumerate(relations):
            lines += [f"def test_relation_{i:02d}():",
                      f"    result = validate_relation(RELATIONS[{i}], production_api())",
                      "    assert result['status'] == 'passed', result", ""]
        output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
        payload = {"schema_version": SCHEMA_VERSION, "version": __version__, "command": "generate",
                   "status": "passed", "output": str(output.relative_to(cwd)), "relations": len(relations)}
        _emit(payload, args.json)
        _audit(cwd, "generate", "passed")
        return 0
    except (OSError, RelationSpecError, ValueError) as exc:
        _emit({"schema_version": SCHEMA_VERSION, "version": __version__, "command": "generate",
               "status": "error", "error": f"{type(exc).__name__}: {exc}"}, True)
        _audit(cwd, "generate", "error")
        return 2


def doctor(args: argparse.Namespace) -> int:
    payload = {"schema_version": SCHEMA_VERSION, "version": __version__, "command": "doctor", "status": "passed",
               "python": platform.python_version(), "platform": platform.platform(),
               "offline_default": True, "network_calls": 0, "model_calls": 0,
               "message": "Deterministic local path is available; optional model/provider adapters are disabled."}
    _emit(payload, args.json)
    return 0


def pilot(args: argparse.Namespace) -> int:
    cwd = Path.cwd()
    try:
        db = _bounded(args.database, cwd, create_parent=True)
        payload = run_pilot(db, args.runs)
        payload["database"] = str(db.relative_to(cwd))
        _emit(payload, args.json)
        _audit(cwd, "pilot", "passed")
        return 0
    except (OSError, ValueError) as exc:
        payload = {"schema_version": SCHEMA_VERSION, "version": __version__, "command": "pilot",
                   "status": "error", "error": f"{type(exc).__name__}: {exc}",
                   "network": False, "model_calls": 0}
        _emit(payload, True)
        _audit(cwd, "pilot", "error")
        return 2


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="zoracleflux", description="Bounded behavioral evidence for supported Python relations.")
    parser.add_argument("--version", action="version", version=__version__)
    sub = parser.add_subparsers(dest="command", required=True)
    pcheck = sub.add_parser("check", help="validate built-in declared relations without executing external source")
    pcheck.add_argument("--source", help="parse a source file only; external code is never imported or executed")
    pcheck.add_argument("--timeout-ms", type=int, default=250)
    pcheck.add_argument("--json", action="store_true")
    pcheck.set_defaults(func=check)
    pgen = sub.add_parser("generate", help="export reviewable runnable pytest checks")
    pgen.add_argument("--output", default="tests/generated/test_zoracleflux_generated.py")
    pgen.add_argument("--json", action="store_true")
    pgen.set_defaults(func=generate)
    pdoc = sub.add_parser("doctor", help="show local capability and safety defaults")
    pdoc.add_argument("--json", action="store_true")
    pdoc.set_defaults(func=doctor)
    ppilot = sub.add_parser("pilot", help="run synthetic checks and record a local SQLite pilot ledger")
    ppilot.add_argument("--database", default=".zoracleflux/pilot.sqlite3")
    ppilot.add_argument("--runs", type=int, default=1)
    ppilot.add_argument("--json", action="store_true")
    ppilot.set_defaults(func=pilot)
    return parser


def main(argv: list[str] | None = None) -> int:
    parsed = build_parser().parse_args(argv)
    return int(parsed.func(parsed))


if __name__ == "__main__":
    raise SystemExit(main())
